/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpinvop.Interfaz;

import com.mxgraph.swing.mxGraphComponent;
import com.mxgraph.view.mxGraph;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import tpinvop.Cadena;
import tpinvop.Simulador;

/**
 *
 * @author lucho
 */
public class VentanaSimulacion extends javax.swing.JFrame {
    private ArrayList<mxGraph> graphs= new ArrayList();
    private List<Object> verticesAnteriores= new ArrayList();
    private mxGraphComponent graphComponent;
    final static private int DISTANCIAX_ENTRE_BLOQUES = 250;
    final static private int DISTANCIAY_ENTRE_BLOQUES = 150;
    final static private int ANCHO_BLOQUE = 220;
    final static private int ALTO_BLOQUE = 100;
    
    final static private int CANTIDAD_AÑOS = 6;
    private int añoInicio;
    
    private Simulador simulador= new Simulador();
    
    /**
     * Creates new form VentanaSimulacion
     * @param cadenas
     */
    public VentanaSimulacion(List<Cadena> cadenas,int añoInicio) {
        initComponents();
        
        this.añoInicio=añoInicio;
        
        int i=1;
        for (Cadena cadena: cadenas){
            JPanel tab = new JPanel();
            mxGraph graph= new mxGraph();
            mxGraphComponent graphComponent = new mxGraphComponent(graph);
            
            tab.setOpaque(false);
            tab.add(this.graphComponent);
            
            tabs.addTab("Linea "+i, tab);
            graphs.add(graph);
            
            i++;
        }
        
    }
    
    Hacer que se genere(mostrarSimulacion) cuando cambias de pestaña
    
    private void mostrarSimulacion(mxGraph graph,int nLinea){
        int posX=0,posY=0;
        Object parent=graph.getDefaultParent();
        Object vertice;
        boolean borrarDeAnteriores=false;
        for (int añoRelativo=0;añoRelativo<CANTIDAD_AÑOS;añoRelativo++){
            for(int nodo=añoRelativo+1;nodo>0;nodo--){
                int añoActual=añoInicio+añoRelativo;
                String textoVertice="Nodo "+nodo+" - "+añoActual+"\n"+simulador.getCantidad(nLinea, nodo, añoRelativo);
                vertice = graph.insertVertex(parent,null,textoVertice,posX,posY,ANCHO_BLOQUE,ALTO_BLOQUE);
                verticesAnteriores.add(vertice);
                
                
                //Agregar los arcos (con los dos primeros de loitsaanteriores)
                //Borra anterior cada dos creo?
                
                
                if (borrarDeAnteriores){
                    verticesAnteriores.remove(0);
                    borrarDeAnteriores=false;
                }
                posY+=DISTANCIAY_ENTRE_BLOQUES;
            }
            posX+=DISTANCIAX_ENTRE_BLOQUES;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
